FROM bdii
LABEL maintainer Enol Fernandez <enol.fernandez@egi.eu>

RUN yum -y install yum-priorities centos-release-openstack-mitaka && \
    yum -y install python-novaclient && \
    yum -y install http://repository.egi.eu/sw/production/cmd-os/1/centos7/x86_64/base/cmd-os-release-1.0.1-1.el7.centos.noarch.rpm && \
    yum -y update && \
    yum -y install http://repository.egi.eu/sw/testing/cmd-os/1/centos7/x86_64/cloud-info-provider-0.8.1-1.el7.centos.noarch.rpm

COPY conf/bdii/cloud-bdii-provider /var/lib/bdii/gip/provider/cloud-info-provider
COPY conf/bdii/openstack.rc /etc/cloud-info-provider/openstack.rc
COPY conf/bdii/openstack.yaml /etc/cloud-info-provider/openstack.yaml
RUN chmod +x /var/lib/bdii/gip/provider/cloud-info-provider

